### ISSUE TITLE
Question of understanding: <targetRole> and <targetType> elements in <function> and <subject>

### ISSUE THREAD

**Issue by BrigitteMichel** [SAA-SDT/eas-schemas#142] opened 2024-07-31 14:57 UTC
## Creator of issue

1. Brigitte Michel (michel@abes.fr)
2. Abes (Agence bibliographique de l'enseignement supérieur = Bibliographic Agency of Higher Education)

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: According to the Tag Library (p. 230 and 232) (+ p.115 and 224), `<targetRole>` and `<targetType>` are optional children of `<function>` and `<subject>`.
I do not understand the possible use of `<targetRole>` and `<targetType>` in the `<function>` (2 elemets not defined in EAC) and `<subject>` elements because in these two cases, the nature of the relationship is already defined by the name of the element itself : there is therefore no Role to define.
Additionally, this seems contradictory to the note on p.116: 'Use `<relation>` with `<targetEntity>` having the @targetType "function" when describing the relationship with the function in more detail,' : this implies that one must choose between two options : an internal description in the EAD file within the `<function>` element or a description of a relationship to an external function.

NB : there is also confusion in this remark between an @targetType attribute, which is not defined in the "Tag Library DRAFT," and the `<targetType>` element defined on p. 232 (source: https://www2.archivists.org/sites/all/files/EAD4.0_DraftTagLibrary.pdf)."

**Comment by florenceclavaud** [comment] 2024-08-01 16:15
>       I do not understand the possible use of `<targetRole>` and `<targetType>` in the `<function>` (2 elemets not defined in EAC) and `<subject>` elements because in these two cases, the nature of the relationship is already defined by the name of the element itself : there is therefore no Role to define.

Well, you may want to say, for example, that the <subject> encoded is the _main_ subject of the records described, which may be quite useful for some users in some situations; or, if the record described is a photograph or series of photographs, or engraving, that it is what the record(s) _represent_. 
Anyway, I am not sure <targetRole> and <relationType> are not somewhat redundant.

**Comment by kerstarno** [comment] 2024-08-02 16:24
This is a duplicate of #125. The original feedback and the comment added here have both been copied to #125. This issue here will hence be closed.

**Closed by kerstarno** 2024-08-02 16:24 UTC
Labels: Duplicate
